"""
train_model.py
---------------
Trains an IsolationForest on the synthetic gait telemetry and produces:
  - Gait_Score (0.0 to 1.0, higher = more anomalous)
  - Tags (e.g. HIGH_CLIPBOARD_USAGE, APP_SWITCH_SPIKE, COGNITIVE_STRAIN_DETECTED)

IsolationForest is trained UNSUPERVISED (it never sees the 'human' /
'bot' / 'coerced_mule' labels) — it just isolates points that are easy
to separate from the bulk of the data via random partitioning. Points
that isolate in fewer splits get higher anomaly scores. We use the
labels only afterward, to evaluate how well the unsupervised score
lines up with ground truth.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
import joblib

from features import (
    FEATURE_COLUMNS,
    extract_feature_matrix,
    fit_scaler,
    save_scaler,
)

# Thresholds used to generate human-readable tags from raw feature values.
# Tune these against your real data distribution once you have it.
TAG_RULES = {
    "HIGH_CLIPBOARD_USAGE": lambda row: row["clipboard_paste_count"] >= 3,
    "APP_SWITCH_SPIKE": lambda row: row["app_switch_count"] >= 4,
    "ROBOTIC_TIMING": lambda row: row["keystroke_interval_std_ms"] < 5,
    "INSTANT_CONFIRM": lambda row: row["session_dwell_time_sec"] < 5,
    "COGNITIVE_STRAIN_DETECTED": lambda row: (
        row["session_dwell_time_sec"] > 100 and row["app_switch_count"] >= 3
    ),
}


def generate_tags(row: pd.Series) -> list[str]:
    # 1. Grab the original tags generated by your existing TAG_RULES
    tags = [tag for tag, rule in TAG_RULES.items() if rule(row)]
    
    # 2. Add the new Flight Time rule
    if row.get("flight_time_mean_ms", 100) < 10.0:
        tags.append("NON_HUMAN_FLIGHT_TIME")
        
    # 3. Add the new Mouse Trajectory rule
    if row.get("mouse_curve_index", 1.0) < 0.1:
        tags.append("ROBOTIC_MOUSE_TRAJECTORY")
        
    # 4. Add the new Time of Day rule
    if row.get("time_of_day_risk", 0.0) > 0.8:
        tags.append("HIGH_RISK_HOURS")
        
    # 5. Return the fully combined list!
    return tags


def train_isolation_forest(
    X_scaled: np.ndarray, contamination: float = 0.08, seed: int = 42
) -> IsolationForest:
    """
    contamination = expected proportion of anomalies in the training set.
    Set this close to (bot_ratio + mule_ratio) used when the synthetic
    data was generated — in production, tune it against a validation
    slice of real flagged accounts instead of guessing.
    """
    model = IsolationForest(
        n_estimators=200,
        contamination=contamination,
        random_state=seed,
        n_jobs=-1,
    )
    model.fit(X_scaled)
    return model


def score_to_gait_score(raw_scores: np.ndarray) -> np.ndarray:
    """
    IsolationForest.decision_function() returns higher = more normal,
    lower/negative = more anomalous. We flip and min-max normalize
    to a 0.0-1.0 Gait_Score where 1.0 = most anomalous, matching the
    spec in the unified decision matrix.
    """
    inverted = -raw_scores
    min_v, max_v = inverted.min(), inverted.max()
    if max_v - min_v < 1e-9:
        return np.zeros_like(inverted)
    return (inverted - min_v) / (max_v - min_v)


def run_training_pipeline(
    telemetry_csv: str = "gait_telemetry_synthetic.csv",
    model_out: str = "gait_isolation_forest.joblib",
    scaler_out: str = "gait_scaler.joblib",
    scored_out: str = "gait_scored_accounts.csv",
) -> pd.DataFrame:
    df = pd.read_csv(telemetry_csv)

    X = extract_feature_matrix(df)
    scaler = fit_scaler(X)
    X_scaled = scaler.transform(X)

    model = train_isolation_forest(X_scaled)

    raw_scores = model.decision_function(X_scaled)
    df["Gait_Score"] = score_to_gait_score(raw_scores)
    df["is_anomaly_prediction"] = model.predict(X_scaled) == -1  # -1 = anomaly
    df["tags"] = df.apply(generate_tags, axis=1)

    joblib.dump(model, model_out)
    save_scaler(scaler, scaler_out)
    df.to_csv(scored_out, index=False)

    return df


def evaluate_against_ground_truth(df: pd.DataFrame) -> None:
    """
    Quick sanity check: since we injected the 'bot' / 'coerced_mule'
    labels ourselves, confirm IsolationForest actually assigns them
    higher Gait_Scores on average than 'human' sessions.
    """
    summary = df.groupby("label")["Gait_Score"].agg(["mean", "median", "count"])
    print("\nGait_Score by true label (sanity check on synthetic data):")
    print(summary)


if __name__ == "__main__":
    scored_df = run_training_pipeline()
    evaluate_against_ground_truth(scored_df)
    print("\nSample high-risk sessions:")
    print(
        scored_df.sort_values("Gait_Score", ascending=False)
        [["account_id", "label", "Gait_Score", "tags"]]
        .head(10)
        .to_string(index=False)
    )